# Generated by Django 6.1.1 on 2026-10-06 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tenure', models.PositiveIntegerField(default=0, help_text='Tenure in months')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaction_frequency', models.PositiveIntegerField(default=0, help_text='Transactions per month')),
                ('complaints', models.PositiveIntegerField(default=0, help_text='Number of complaints')),
                ('service_usage', models.FloatField(default=0.0, help_text='Service usage score (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
